"""Initial schema

Revision ID: 293b3517b6ac
Revises: None
Create Date: 2026-07-16 12:59:28.677345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293b3517b6ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=True),
    sa.Column('narrative_style', sa.Text(), nullable=True),
    sa.Column('current_scene_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('mood_tags', sa.Text(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provenance', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'entity_type', 'canonical_name', name='uq_campaign_entity_name')
    )
    op.create_table('facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=255), nullable=False),
    sa.Column('object_value', sa.Text(), nullable=True),
    sa.Column('truth_status', sa.String(length=50), nullable=False),
    sa.Column('source_turn_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('tension', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beliefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=True),
    sa.Column('proposition', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_turn_id', sa.Integer(), nullable=True),
    sa.Column('source_character_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_character_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by'], ['beliefs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('source_turn_id', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('face_description', sa.Text(), nullable=True),
    sa.Column('body_description', sa.Text(), nullable=True),
    sa.Column('immutable_features', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('fears', sa.Text(), nullable=True),
    sa.Column('desires', sa.Text(), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('speech_patterns', sa.Text(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('backstory_public', sa.Text(), nullable=True),
    sa.Column('backstory_secret', sa.Text(), nullable=True),
    sa.Column('emotional_state', sa.Text(), nullable=True),
    sa.Column('current_location_id', sa.String(length=36), nullable=True),
    sa.Column('current_intentions', sa.Text(), nullable=True),
    sa.Column('visual_profile', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('creatures',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('threat_level', sa.String(length=100), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('world_time', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=False),
    sa.Column('source_turns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('hierarchy', sa.Text(), nullable=True),
    sa.Column('membership_rules', sa.Text(), nullable=True),
    sa.Column('reputation', sa.Text(), nullable=True),
    sa.Column('secret_agenda', sa.Text(), nullable=True),
    sa.Column('leader_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('items',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('physical_properties', sa.Text(), nullable=True),
    sa.Column('magical_properties', sa.Text(), nullable=True),
    sa.Column('value_estimate', sa.Text(), nullable=True),
    sa.Column('current_owner_id', sa.String(length=36), nullable=True),
    sa.Column('current_location_id', sa.String(length=36), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('lore', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_owner_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('locations',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('access_rules', sa.Text(), nullable=True),
    sa.Column('parent_location_id', sa.String(length=36), nullable=True),
    sa.Column('climate', sa.Text(), nullable=True),
    sa.Column('notable_features', sa.Text(), nullable=True),
    sa.Column('danger_level', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playback_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'entity_id', name='uq_scene_participant')
    )
    op.create_table('scene_theses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('thesis_type', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('source_turn_id', sa.Integer(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('related_entity_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_turn_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposed_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_edit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_assertions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('source_turn_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('intensity IS NULL OR (intensity >= -1.0 AND intensity <= 1.0)', name='ck_relationship_intensity'),
    sa.CheckConstraint('subject_id != object_id', name='ck_self_relationship'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['relationship_assertions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_assertions')
    op.drop_table('proposed_changes')
    op.drop_table('event_participants')
    op.drop_table('turns')
    op.drop_table('scene_theses')
    op.drop_table('scene_participants')
    op.drop_table('playback_history')
    op.drop_table('media_assets')
    op.drop_table('locations')
    op.drop_table('items')
    op.drop_table('factions')
    op.drop_table('events')
    op.drop_table('creatures')
    op.drop_table('characters')
    op.drop_table('character_goals')
    op.drop_table('beliefs')
    op.drop_table('scenes')
    op.drop_table('provider_configs')
    op.drop_table('facts')
    op.drop_table('entities')
    op.drop_table('tracks')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
